In [9]:
import gym
import numpy as np
import time

# Create FrozenLake environment
env = gym.make('FrozenLake-v0')

STATES = env.observation_space.n
ACTIONS = env.action_space.n
# Explore environment
print(STATES)
print(ACTIONS)

16
4


In [10]:
env.reset()
for _ in range(5):
    env.render()
    action = env.step(env.action_space.sample()) # take a random action
    # F: frozen, H: hole, S: start, G: goal
    print("New state: {}, Reward: {}, Done: {}, Info: {}".format(
        action[0], action[1], action[2], action[3]))
env.close()


SFFF
FHFH
FFFH
HFFG
New state: 0, Reward: 0.0, Done: False, Info: {'prob': 0.3333333333333333}
  (Left)
SFFF
FHFH
FFFH
HFFG
New state: 1, Reward: 0.0, Done: False, Info: {'prob': 0.3333333333333333}
  (Up)
SFFF
FHFH
FFFH
HFFG
New state: 2, Reward: 0.0, Done: False, Info: {'prob': 0.3333333333333333}
  (Up)
SFFF
FHFH
FFFH
HFFG
New state: 6, Reward: 0.0, Done: False, Info: {'prob': 0.3333333333333333}
  (Down)
SFFF
FHFH
FFFH
HFFG
New state: 2, Reward: 0.0, Done: False, Info: {'prob': 0.3333333333333333}


In [12]:
Q = np.zeros((STATES, ACTIONS))  # create a matrix with all 0 values 
print(Q)

# Define constants
EPISODES = 1500
MAX_STEPS = 100

LEARNING_RATE = 1.0
GAMMA = 0.9

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
